### ISSUE TITLE
[Feature request] ssh url 

### ISSUE THREAD

**Issue by lengyijun** [KaustubhPatange/git-open#5]
```
git clone git@github.com:KaustubhPatange/git-open.git
git-open // a blank window
```

**Comment by KaustubhPatange** [comment]
Yup, it doesn't support repositories cloned via ssh. 

I currently don't have the time to maintain this project, so if you can or want to contribute to this feature, feel free to send a PR.

**Comment by lengyijun** [comment]
I'm sorry I switched to https://github.com/oren0e/gitopen
